const data = [
  {
    id: 0,
    productName: "Syltherine 1",
    image: "../desafio2/images/image1.png",
    price: "2500000",
    priceDiscount: "3500000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_30.png",
    description: "Stylish cafe chair.",
  },
  {
    id: 1,
    productName: "Leviosa 2",
    image: "../desafio2/images/image2.png",
    price: "2500000",
    priceDiscount: "",
    condition: false,
    conditionPrice: "",
    description: "Stylish cafe chair.",
  },
  {
    id: 2,
    productName: "Lolito 3",
    image: "../desafio2/images/image3.png",
    price: "7000000",
    priceDiscount: "14000000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_50.png",
    description: "Luxury big safe.",
  },
  {
    id: 3,
    productName: "Respira 4",
    image: "../desafio2/images/image4.png",
    price: "500000",
    priceDiscount: "",
    condition: true,
    conditionPrice: "../desafio2/images/New.png",
    description: "Outdoor bar table and stool.",
  },
  {
    id: 4,
    productName: "Syltherine 5",
    image: "../desafio2/images/image1.png",
    price: "2500000",
    priceDiscount: "3500000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_30.png",
    description: "Stylish cafe chair.",
  },
  {
    id: 5,
    productName: "Leviosa 6",
    image: "../desafio2/images/image2.png",
    price: "2500000",
    priceDiscount: "",
    condition: false,
    conditionPrice: "",
    description: "Stylish cafe chair.",
  },
  {
    id: 6,
    productName: "Lolito 7",
    image: "../desafio2/images/image3.png",
    price: "7000000",
    priceDiscount: "14000000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_50.png",
    description: "Luxury big safe.",
  },
  {
    id: 7,
    productName: "Respira 8",
    image: "../desafio2/images/image4.png",
    price: "500000",
    priceDiscount: "",
    condition: true,
    conditionPrice: "../desafio2/images/New.png",
    description: "Outdoor bar table and stool.",
  },
  {
    id: 8,
    productName: "Syltherine 9",
    image: "../desafio2/images/image1.png",
    price: "2500000",
    priceDiscount: "3500000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_30.png",
    description: "Stylish cafe chair.",
  },
  {
    id: 9,
    productName: "Leviosa 10",
    image: "../desafio2/images/image2.png",
    price: "2500000",
    priceDiscount: "",
    condition: false,
    conditionPrice: "",
    description: "Stylish cafe chair.",
  },
  {
    id: 10,
    productName: "Lolito 11",
    image: "../desafio2/images/image3.png",
    price: "7000000",
    priceDiscount: "14000000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_50.png",
    description: "Luxury big safe.",
  },
  {
    id: 11,
    productName: "Respira 12",
    image: "../desafio2/images/image4.png",
    price: "500000",
    priceDiscount: "",
    condition: true,
    conditionPrice: "../desafio2/images/New.png",
    description: "Outdoor bar table and stool.",
  },
  {
    id: 12,
    productName: "Syltherine 13",
    image: "../desafio2/images/image1.png",
    price: "2500000",
    priceDiscount: "3500000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_30.png",
    description: "Stylish cafe chair.",
  },
  {
    id: 13,
    productName: "Leviosa 14",
    image: "../desafio2/images/image2.png",
    price: "2500000",
    priceDiscount: "",
    condition: false,
    conditionPrice: "",
    description: "Stylish cafe chair.",
  },
  {
    id: 14,
    productName: "Lolito 15",
    image: "../desafio2/images/image3.png",
    price: "7000000",
    priceDiscount: "14000000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_50.png",
    description: "Luxury big safe.",
  },
  {
    id: 15,
    productName: "Respira 16",
    image: "../desafio2/images/image4.png",
    price: "500000",
    priceDiscount: "",
    condition: true,
    conditionPrice: "../desafio2/images/New.png",
    description: "Outdoor bar table and stool.",
  },
  {
    id: 16,
    productName: "Syltherine 17",
    image: "../desafio2/images/image1.png",
    price: "2500000",
    priceDiscount: "3500000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_30.png",
    description: "Stylish cafe chair.",
  },
  {
    id: 17,
    productName: "Leviosa 18",
    image: "../desafio2/images/image2.png",
    price: "2500000",
    priceDiscount: "",
    condition: false,
    conditionPrice: "",
    description: "Stylish cafe chair.",
  },
  {
    id: 18,
    productName: "Lolito 19",
    image: "../desafio2/images/image3.png",
    price: "7000000",
    priceDiscount: "14000000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_50.png",
    description: "Luxury big safe.",
  },
  {
    id: 19,
    productName: "Respira 20",
    image: "../desafio2/images/image4.png",
    price: "500000",
    priceDiscount: "",
    condition: true,
    conditionPrice: "../desafio2/images/New.png",
    description: "Outdoor bar table and stool.",
  },
  {
    id: 20,
    productName: "Syltherine 21",
    image: "../desafio2/images/image1.png",
    price: "2500000",
    priceDiscount: "3500000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_30.png",
    description: "Stylish cafe chair.",
  },
  {
    id: 21,
    productName: "Leviosa 22",
    image: "../desafio2/images/image2.png",
    price: "2500000",
    priceDiscount: "",
    condition: false,
    conditionPrice: "",
    description: "Stylish cafe chair.",
  },
  {
    id: 22,
    productName: "Lolito 23",
    image: "../desafio2/images/image3.png",
    price: "7000000",
    priceDiscount: "14000000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_50.png",
    description: "Luxury big safe.",
  },
  {
    id: 23,
    productName: "Respira 24",
    image: "../desafio2/images/image4.png",
    price: "500000",
    priceDiscount: "",
    condition: true,
    conditionPrice: "../desafio2/images/New.png",
    description: "Outdoor bar table and stool.",
  },
  {
    id: 24,
    productName: "Syltherine 25",
    image: "../desafio2/images/image1.png",
    price: "2500000",
    priceDiscount: "3500000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_30.png",
    description: "Stylish cafe chair.",
  },
  {
    id: 25,
    productName: "Leviosa 26",
    image: "../desafio2/images/image2.png",
    price: "2500000",
    priceDiscount: "",
    condition: false,
    conditionPrice: "",
    description: "Stylish cafe chair.",
  },
  {
    id: 26,
    productName: "Lolito 27",
    image: "../desafio2/images/image3.png",
    price: "7000000",
    priceDiscount: "14000000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_50.png",
    description: "Luxury big safe.",
  },
  {
    id: 27,
    productName: "Respira 28",
    image: "../desafio2/images/image4.png",
    price: "500000",
    priceDiscount: "",
    condition: true,
    conditionPrice: "../desafio2/images/New.png",
    description: "Outdoor bar table and stool.",
  },
  {
    id: 28,
    productName: "Syltherine 29",
    image: "../desafio2/images/image1.png",
    price: "2500000",
    priceDiscount: "3500000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_30.png",
    description: "Stylish cafe chair.",
  },
  {
    id: 29,
    productName: "Leviosa 30",
    image: "../desafio2/images/image2.png",
    price: "2500000",
    priceDiscount: "",
    condition: false,
    conditionPrice: "",
    description: "Stylish cafe chair.",
  },
  {
    id: 30,
    productName: "Lolito 31",
    image: "../desafio2/images/image3.png",
    price: "7000000",
    priceDiscount: "14000000",
    condition: true,
    conditionPrice: "../desafio2/images/Discount_50.png",
    description: "Luxury big safe.",
  },
  {
    id: 31,
    productName: "Respira 32",
    image: "../desafio2/images/image4.png",
    price: "500000",
    priceDiscount: "",
    condition: true,
    conditionPrice: "../desafio2/images/New.png",
    description: "Outdoor bar table and stool.",
  },
];
